// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::schema;
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `secret_backend_command`-Secret backend command for API keys
    SECRET_BACKEND_COMMAND = SalukiAnnotation {
        schema: &schema::SECRET_BACKEND_COMMAND,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: Some(r#""/etc/datadog-agent/secret-backend.sh""#),
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `secret_refresh_on_api_key_failure_interval`-Secret refresh interval (min) on API-key failure
    SECRET_REFRESH_ON_API_KEY_FAILURE_INTERVAL = SalukiAnnotation {
        schema: &schema::SECRET_REFRESH_ON_API_KEY_FAILURE_INTERVAL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: Some("5"),
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
