// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
// Regenerate by running `cargo build -p datadog-agent-config`.
#![allow(clippy::all, dead_code, unused)]

use serde::de::DeserializeOwned;

use crate::datadog_configuration::DatadogConfiguration;

/// Generated trait with one method per supported Datadog configuration key.
///
/// The hand-written translator implements this trait. Because there are no default method bodies,
/// the compiler forces the translator to give every supported key an explicit destination.
pub trait DatadogConfigConsumer {
    /// Consume the `additional_endpoints` value.
    fn consume_additional_endpoints(&mut self, value: serde_json::Value);

    /// Consume the `agent_ipc.grpc_max_message_size` value.
    fn consume_agent_ipc_grpc_max_message_size(&mut self, value: i64);

    /// Consume the `allow_arbitrary_tags` value.
    fn consume_allow_arbitrary_tags(&mut self, value: bool);

    /// Consume the `api_key` value.
    fn consume_api_key(&mut self, value: Option<String>);

    /// Consume the `apm_config.obfuscation.credit_cards.enabled` value.
    fn consume_apm_config_obfuscation_credit_cards_enabled(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.credit_cards.keep_values` value.
    fn consume_apm_config_obfuscation_credit_cards_keep_values(&mut self, value: Vec<String>);

    /// Consume the `apm_config.obfuscation.credit_cards.luhn` value.
    fn consume_apm_config_obfuscation_credit_cards_luhn(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.elasticsearch.enabled` value.
    fn consume_apm_config_obfuscation_elasticsearch_enabled(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.elasticsearch.keep_values` value.
    fn consume_apm_config_obfuscation_elasticsearch_keep_values(&mut self, value: Vec<String>);

    /// Consume the `apm_config.obfuscation.elasticsearch.obfuscate_sql_values` value.
    fn consume_apm_config_obfuscation_elasticsearch_obfuscate_sql_values(&mut self, value: Vec<String>);

    /// Consume the `apm_config.obfuscation.http.remove_paths_with_digits` value.
    fn consume_apm_config_obfuscation_http_remove_paths_with_digits(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.http.remove_query_string` value.
    fn consume_apm_config_obfuscation_http_remove_query_string(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.memcached.enabled` value.
    fn consume_apm_config_obfuscation_memcached_enabled(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.memcached.keep_command` value.
    fn consume_apm_config_obfuscation_memcached_keep_command(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.mongodb.enabled` value.
    fn consume_apm_config_obfuscation_mongodb_enabled(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.mongodb.keep_values` value.
    fn consume_apm_config_obfuscation_mongodb_keep_values(&mut self, value: Vec<String>);

    /// Consume the `apm_config.obfuscation.mongodb.obfuscate_sql_values` value.
    fn consume_apm_config_obfuscation_mongodb_obfuscate_sql_values(&mut self, value: Vec<String>);

    /// Consume the `apm_config.obfuscation.opensearch.enabled` value.
    fn consume_apm_config_obfuscation_opensearch_enabled(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.opensearch.keep_values` value.
    fn consume_apm_config_obfuscation_opensearch_keep_values(&mut self, value: Vec<String>);

    /// Consume the `apm_config.obfuscation.opensearch.obfuscate_sql_values` value.
    fn consume_apm_config_obfuscation_opensearch_obfuscate_sql_values(&mut self, value: Vec<String>);

    /// Consume the `apm_config.obfuscation.redis.enabled` value.
    fn consume_apm_config_obfuscation_redis_enabled(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.redis.remove_all_args` value.
    fn consume_apm_config_obfuscation_redis_remove_all_args(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.valkey.enabled` value.
    fn consume_apm_config_obfuscation_valkey_enabled(&mut self, value: bool);

    /// Consume the `apm_config.obfuscation.valkey.remove_all_args` value.
    fn consume_apm_config_obfuscation_valkey_remove_all_args(&mut self, value: bool);

    /// Consume the `bind_host` value.
    fn consume_bind_host(&mut self, value: Option<String>);

    /// Consume the `cmd_port` value.
    fn consume_cmd_port(&mut self, value: i64);

    /// Consume the `cri_connection_timeout` value.
    fn consume_cri_connection_timeout(&mut self, value: i64);

    /// Consume the `cri_query_timeout` value.
    fn consume_cri_query_timeout(&mut self, value: i64);

    /// Consume the `data_plane.api_listen_address` value.
    fn consume_data_plane_api_listen_address(&mut self, value: Option<String>);

    /// Consume the `data_plane.dogstatsd.aggregator_tag_filter_cache_capacity` value.
    fn consume_data_plane_dogstatsd_aggregator_tag_filter_cache_capacity(&mut self, value: i64);

    /// Consume the `data_plane.log_file` value.
    fn consume_data_plane_log_file(&mut self, value: Option<String>);

    /// Consume the `data_plane.otlp.proxy.logs.enabled` value.
    fn consume_data_plane_otlp_proxy_logs_enabled(&mut self, value: bool);

    /// Consume the `data_plane.otlp.proxy.metrics.enabled` value.
    fn consume_data_plane_otlp_proxy_metrics_enabled(&mut self, value: bool);

    /// Consume the `data_plane.otlp.proxy.traces.enabled` value.
    fn consume_data_plane_otlp_proxy_traces_enabled(&mut self, value: bool);

    /// Consume the `data_plane.remote_agent_enabled` value.
    fn consume_data_plane_remote_agent_enabled(&mut self, value: bool);

    /// Consume the `data_plane.secure_api_listen_address` value.
    fn consume_data_plane_secure_api_listen_address(&mut self, value: Option<String>);

    /// Consume the `data_plane.use_new_config_stream_endpoint` value.
    fn consume_data_plane_use_new_config_stream_endpoint(&mut self, value: bool);

    /// Consume the `dd_url` value.
    fn consume_dd_url(&mut self, value: Option<String>);

    /// Consume the `dogstatsd_buffer_size` value.
    fn consume_dogstatsd_buffer_size(&mut self, value: i64);

    /// Consume the `dogstatsd_capture_depth` value.
    fn consume_dogstatsd_capture_depth(&mut self, value: i64);

    /// Consume the `dogstatsd_capture_path` value.
    fn consume_dogstatsd_capture_path(&mut self, value: Option<String>);

    /// Consume the `dogstatsd_context_expiry_seconds` value.
    fn consume_dogstatsd_context_expiry_seconds(&mut self, value: i64);

    /// Consume the `dogstatsd_entity_id_precedence` value.
    fn consume_dogstatsd_entity_id_precedence(&mut self, value: bool);

    /// Consume the `dogstatsd_eol_required` value.
    fn consume_dogstatsd_eol_required(&mut self, value: Vec<String>);

    /// Consume the `dogstatsd_flush_incomplete_buckets` value.
    fn consume_dogstatsd_flush_incomplete_buckets(&mut self, value: bool);

    /// Consume the `dogstatsd_log_file` value.
    fn consume_dogstatsd_log_file(&mut self, value: Option<String>);

    /// Consume the `dogstatsd_log_file_max_rolls` value.
    fn consume_dogstatsd_log_file_max_rolls(&mut self, value: i64);

    /// Consume the `dogstatsd_log_file_max_size` value.
    fn consume_dogstatsd_log_file_max_size(&mut self, value: Option<String>);

    /// Consume the `dogstatsd_logging_enabled` value.
    fn consume_dogstatsd_logging_enabled(&mut self, value: bool);

    /// Consume the `dogstatsd_mapper_cache_size` value.
    fn consume_dogstatsd_mapper_cache_size(&mut self, value: i64);

    /// Consume the `dogstatsd_mapper_profiles` value.
    fn consume_dogstatsd_mapper_profiles(&mut self, value: serde_json::Value);

    /// Consume the `dogstatsd_metrics_stats_enable` value.
    fn consume_dogstatsd_metrics_stats_enable(&mut self, value: bool);

    /// Consume the `dogstatsd_no_aggregation_pipeline` value.
    fn consume_dogstatsd_no_aggregation_pipeline(&mut self, value: bool);

    /// Consume the `dogstatsd_non_local_traffic` value.
    fn consume_dogstatsd_non_local_traffic(&mut self, value: bool);

    /// Consume the `dogstatsd_origin_detection` value.
    fn consume_dogstatsd_origin_detection(&mut self, value: bool);

    /// Consume the `dogstatsd_origin_detection_client` value.
    fn consume_dogstatsd_origin_detection_client(&mut self, value: bool);

    /// Consume the `dogstatsd_origin_optout_enabled` value.
    fn consume_dogstatsd_origin_optout_enabled(&mut self, value: bool);

    /// Consume the `dogstatsd_port` value.
    fn consume_dogstatsd_port(&mut self, value: i64);

    /// Consume the `dogstatsd_so_rcvbuf` value.
    fn consume_dogstatsd_so_rcvbuf(&mut self, value: i64);

    /// Consume the `dogstatsd_socket` value.
    fn consume_dogstatsd_socket(&mut self, value: Option<String>);

    /// Consume the `dogstatsd_stream_log_too_big` value.
    fn consume_dogstatsd_stream_log_too_big(&mut self, value: bool);

    /// Consume the `dogstatsd_stream_socket` value.
    fn consume_dogstatsd_stream_socket(&mut self, value: Option<String>);

    /// Consume the `dogstatsd_string_interner_size` value.
    fn consume_dogstatsd_string_interner_size(&mut self, value: i64);

    /// Consume the `dogstatsd_tag_cardinality` value.
    fn consume_dogstatsd_tag_cardinality(&mut self, value: Option<String>);

    /// Consume the `dogstatsd_tags` value.
    fn consume_dogstatsd_tags(&mut self, value: Vec<String>);

    /// Consume the `enable_payloads.events` value.
    fn consume_enable_payloads_events(&mut self, value: bool);

    /// Consume the `enable_payloads.series` value.
    fn consume_enable_payloads_series(&mut self, value: bool);

    /// Consume the `enable_payloads.service_checks` value.
    fn consume_enable_payloads_service_checks(&mut self, value: bool);

    /// Consume the `enable_payloads.sketches` value.
    fn consume_enable_payloads_sketches(&mut self, value: bool);

    /// Consume the `env` value.
    fn consume_env(&mut self, value: Option<String>);

    /// Consume the `forwarder_apikey_validation_interval` value.
    fn consume_forwarder_apikey_validation_interval(&mut self, value: i64);

    /// Consume the `forwarder_backoff_base` value.
    fn consume_forwarder_backoff_base(&mut self, value: i64);

    /// Consume the `forwarder_backoff_factor` value.
    fn consume_forwarder_backoff_factor(&mut self, value: i64);

    /// Consume the `forwarder_backoff_max` value.
    fn consume_forwarder_backoff_max(&mut self, value: i64);

    /// Consume the `forwarder_connection_reset_interval` value.
    fn consume_forwarder_connection_reset_interval(&mut self, value: i64);

    /// Consume the `forwarder_high_prio_buffer_size` value.
    fn consume_forwarder_high_prio_buffer_size(&mut self, value: i64);

    /// Consume the `forwarder_http_protocol` value.
    fn consume_forwarder_http_protocol(&mut self, value: Option<String>);

    /// Consume the `forwarder_max_concurrent_requests` value.
    fn consume_forwarder_max_concurrent_requests(&mut self, value: i64);

    /// Consume the `forwarder_num_workers` value.
    fn consume_forwarder_num_workers(&mut self, value: i64);

    /// Consume the `forwarder_outdated_file_in_days` value.
    fn consume_forwarder_outdated_file_in_days(&mut self, value: i64);

    /// Consume the `forwarder_recovery_interval` value.
    fn consume_forwarder_recovery_interval(&mut self, value: i64);

    /// Consume the `forwarder_recovery_reset` value.
    fn consume_forwarder_recovery_reset(&mut self, value: bool);

    /// Consume the `forwarder_retry_queue_capacity_time_interval_sec` value.
    fn consume_forwarder_retry_queue_capacity_time_interval_sec(&mut self, value: i64);

    /// Consume the `forwarder_retry_queue_max_size` value.
    fn consume_forwarder_retry_queue_max_size(&mut self, value: i64);

    /// Consume the `forwarder_retry_queue_payloads_max_size` value.
    fn consume_forwarder_retry_queue_payloads_max_size(&mut self, value: i64);

    /// Consume the `forwarder_storage_max_disk_ratio` value.
    fn consume_forwarder_storage_max_disk_ratio(&mut self, value: f64);

    /// Consume the `forwarder_storage_max_size_in_bytes` value.
    fn consume_forwarder_storage_max_size_in_bytes(&mut self, value: i64);

    /// Consume the `forwarder_storage_path` value.
    fn consume_forwarder_storage_path(&mut self, value: Option<String>);

    /// Consume the `forwarder_timeout` value.
    fn consume_forwarder_timeout(&mut self, value: i64);

    /// Consume the `histogram_aggregates` value.
    fn consume_histogram_aggregates(&mut self, value: Vec<String>);

    /// Consume the `histogram_copy_to_distribution` value.
    fn consume_histogram_copy_to_distribution(&mut self, value: bool);

    /// Consume the `histogram_copy_to_distribution_prefix` value.
    fn consume_histogram_copy_to_distribution_prefix(&mut self, value: Option<String>);

    /// Consume the `log_format_rfc3339` value.
    fn consume_log_format_rfc3339(&mut self, value: bool);

    /// Consume the `log_level` value.
    fn consume_log_level(&mut self, value: Option<String>);

    /// Consume the `log_payloads` value.
    fn consume_log_payloads(&mut self, value: bool);

    /// Consume the `metric_filterlist` value.
    fn consume_metric_filterlist(&mut self, value: Vec<String>);

    /// Consume the `metric_filterlist_match_prefix` value.
    fn consume_metric_filterlist_match_prefix(&mut self, value: bool);

    /// Consume the `min_tls_version` value.
    fn consume_min_tls_version(&mut self, value: Option<String>);

    /// Consume the `multi_region_failover.api_key` value.
    fn consume_multi_region_failover_api_key(&mut self, value: Option<String>);

    /// Consume the `multi_region_failover.dd_url` value.
    fn consume_multi_region_failover_dd_url(&mut self, value: Option<String>);

    /// Consume the `multi_region_failover.enabled` value.
    fn consume_multi_region_failover_enabled(&mut self, value: bool);

    /// Consume the `multi_region_failover.failover_metrics` value.
    fn consume_multi_region_failover_failover_metrics(&mut self, value: bool);

    /// Consume the `multi_region_failover.metric_allowlist` value.
    fn consume_multi_region_failover_metric_allowlist(&mut self, value: Vec<String>);

    /// Consume the `multi_region_failover.site` value.
    fn consume_multi_region_failover_site(&mut self, value: Option<String>);

    /// Consume the `no_proxy_nonexact_match` value.
    fn consume_no_proxy_nonexact_match(&mut self, value: bool);

    /// Consume the `observability_pipelines_worker.metrics.enabled` value.
    fn consume_observability_pipelines_worker_metrics_enabled(&mut self, value: bool);

    /// Consume the `observability_pipelines_worker.metrics.url` value.
    fn consume_observability_pipelines_worker_metrics_url(&mut self, value: Option<String>);

    /// Consume the `origin_detection_unified` value.
    fn consume_origin_detection_unified(&mut self, value: bool);

    /// Consume the `otlp_config.logs.enabled` value.
    fn consume_otlp_config_logs_enabled(&mut self, value: bool);

    /// Consume the `otlp_config.metrics.enabled` value.
    fn consume_otlp_config_metrics_enabled(&mut self, value: bool);

    /// Consume the `otlp_config.receiver.protocols.grpc.endpoint` value.
    fn consume_otlp_config_receiver_protocols_grpc_endpoint(&mut self, value: Option<String>);

    /// Consume the `otlp_config.receiver.protocols.grpc.max_recv_msg_size_mib` value.
    fn consume_otlp_config_receiver_protocols_grpc_max_recv_msg_size_mib(&mut self, value: i64);

    /// Consume the `otlp_config.receiver.protocols.grpc.transport` value.
    fn consume_otlp_config_receiver_protocols_grpc_transport(&mut self, value: Option<String>);

    /// Consume the `otlp_config.receiver.protocols.http.endpoint` value.
    fn consume_otlp_config_receiver_protocols_http_endpoint(&mut self, value: Option<String>);

    /// Consume the `otlp_config.traces.enabled` value.
    fn consume_otlp_config_traces_enabled(&mut self, value: bool);

    /// Consume the `otlp_config.traces.internal_port` value.
    fn consume_otlp_config_traces_internal_port(&mut self, value: i64);

    /// Consume the `otlp_config.traces.probabilistic_sampler.sampling_percentage` value.
    fn consume_otlp_config_traces_probabilistic_sampler_sampling_percentage(&mut self, value: f64);

    /// Consume the `provider_kind` value.
    fn consume_provider_kind(&mut self, value: Option<String>);

    /// Consume the `proxy.http` value.
    fn consume_proxy_http(&mut self, value: Option<String>);

    /// Consume the `proxy.https` value.
    fn consume_proxy_https(&mut self, value: Option<String>);

    /// Consume the `proxy.no_proxy` value.
    fn consume_proxy_no_proxy(&mut self, value: Vec<String>);

    /// Consume the `secret_backend_command` value.
    fn consume_secret_backend_command(&mut self, value: Option<String>);

    /// Consume the `secret_refresh_on_api_key_failure_interval` value.
    fn consume_secret_refresh_on_api_key_failure_interval(&mut self, value: i64);

    /// Consume the `serializer_compressor_kind` value.
    fn consume_serializer_compressor_kind(&mut self, value: Option<String>);

    /// Consume the `serializer_max_payload_size` value.
    fn consume_serializer_max_payload_size(&mut self, value: i64);

    /// Consume the `serializer_max_series_payload_size` value.
    fn consume_serializer_max_series_payload_size(&mut self, value: i64);

    /// Consume the `serializer_max_series_points_per_payload` value.
    fn consume_serializer_max_series_points_per_payload(&mut self, value: i64);

    /// Consume the `serializer_max_series_uncompressed_payload_size` value.
    fn consume_serializer_max_series_uncompressed_payload_size(&mut self, value: i64);

    /// Consume the `serializer_max_uncompressed_payload_size` value.
    fn consume_serializer_max_uncompressed_payload_size(&mut self, value: i64);

    /// Consume the `serializer_zstd_compressor_level` value.
    fn consume_serializer_zstd_compressor_level(&mut self, value: i64);

    /// Consume the `site` value.
    fn consume_site(&mut self, value: Option<String>);

    /// Consume the `skip_ssl_validation` value.
    fn consume_skip_ssl_validation(&mut self, value: bool);

    /// Consume the `sslkeylogfile` value.
    fn consume_sslkeylogfile(&mut self, value: Option<String>);

    /// Consume the `statsd_forward_host` value.
    fn consume_statsd_forward_host(&mut self, value: Option<String>);

    /// Consume the `statsd_forward_port` value.
    fn consume_statsd_forward_port(&mut self, value: i64);

    /// Consume the `statsd_metric_blocklist` value.
    fn consume_statsd_metric_blocklist(&mut self, value: Vec<String>);

    /// Consume the `statsd_metric_blocklist_match_prefix` value.
    fn consume_statsd_metric_blocklist_match_prefix(&mut self, value: bool);

    /// Consume the `statsd_metric_namespace` value.
    fn consume_statsd_metric_namespace(&mut self, value: Option<String>);

    /// Consume the `statsd_metric_namespace_blacklist` value.
    fn consume_statsd_metric_namespace_blacklist(&mut self, value: Vec<String>);

    /// Consume the `syslog_rfc` value.
    fn consume_syslog_rfc(&mut self, value: bool);

    /// Consume the `syslog_uri` value.
    fn consume_syslog_uri(&mut self, value: Option<String>);

    /// Consume the `use_proxy_for_cloud_metadata` value.
    fn consume_use_proxy_for_cloud_metadata(&mut self, value: bool);

    /// Consume the `use_v2_api.series` value.
    fn consume_use_v2_api_series(&mut self, value: bool);

    /// Consume the `vector.metrics.enabled` value.
    fn consume_vector_metrics_enabled(&mut self, value: bool);

    /// Consume the `vector.metrics.url` value.
    fn consume_vector_metrics_url(&mut self, value: Option<String>);

    /// Consume the `vsock_addr` value.
    fn consume_vsock_addr(&mut self, value: Option<String>);
}

/// Drive a consumer over every supported key in a [`DatadogConfiguration`].
pub fn drive(config: &DatadogConfiguration, consumer: &mut impl DatadogConfigConsumer) {
    let root = serde_json::to_value(config).expect("DatadogConfiguration always serializes");
    consumer.consume_additional_endpoints(witness_get(&root, "additional_endpoints"));
    consumer.consume_agent_ipc_grpc_max_message_size(witness_get(&root, "agent_ipc.grpc_max_message_size"));
    consumer.consume_allow_arbitrary_tags(witness_get(&root, "allow_arbitrary_tags"));
    consumer.consume_api_key(witness_get(&root, "api_key"));
    consumer.consume_apm_config_obfuscation_credit_cards_enabled(witness_get(
        &root,
        "apm_config.obfuscation.credit_cards.enabled",
    ));
    consumer.consume_apm_config_obfuscation_credit_cards_keep_values(witness_get(
        &root,
        "apm_config.obfuscation.credit_cards.keep_values",
    ));
    consumer.consume_apm_config_obfuscation_credit_cards_luhn(witness_get(
        &root,
        "apm_config.obfuscation.credit_cards.luhn",
    ));
    consumer.consume_apm_config_obfuscation_elasticsearch_enabled(witness_get(
        &root,
        "apm_config.obfuscation.elasticsearch.enabled",
    ));
    consumer.consume_apm_config_obfuscation_elasticsearch_keep_values(witness_get(
        &root,
        "apm_config.obfuscation.elasticsearch.keep_values",
    ));
    consumer.consume_apm_config_obfuscation_elasticsearch_obfuscate_sql_values(witness_get(
        &root,
        "apm_config.obfuscation.elasticsearch.obfuscate_sql_values",
    ));
    consumer.consume_apm_config_obfuscation_http_remove_paths_with_digits(witness_get(
        &root,
        "apm_config.obfuscation.http.remove_paths_with_digits",
    ));
    consumer.consume_apm_config_obfuscation_http_remove_query_string(witness_get(
        &root,
        "apm_config.obfuscation.http.remove_query_string",
    ));
    consumer.consume_apm_config_obfuscation_memcached_enabled(witness_get(
        &root,
        "apm_config.obfuscation.memcached.enabled",
    ));
    consumer.consume_apm_config_obfuscation_memcached_keep_command(witness_get(
        &root,
        "apm_config.obfuscation.memcached.keep_command",
    ));
    consumer
        .consume_apm_config_obfuscation_mongodb_enabled(witness_get(&root, "apm_config.obfuscation.mongodb.enabled"));
    consumer.consume_apm_config_obfuscation_mongodb_keep_values(witness_get(
        &root,
        "apm_config.obfuscation.mongodb.keep_values",
    ));
    consumer.consume_apm_config_obfuscation_mongodb_obfuscate_sql_values(witness_get(
        &root,
        "apm_config.obfuscation.mongodb.obfuscate_sql_values",
    ));
    consumer.consume_apm_config_obfuscation_opensearch_enabled(witness_get(
        &root,
        "apm_config.obfuscation.opensearch.enabled",
    ));
    consumer.consume_apm_config_obfuscation_opensearch_keep_values(witness_get(
        &root,
        "apm_config.obfuscation.opensearch.keep_values",
    ));
    consumer.consume_apm_config_obfuscation_opensearch_obfuscate_sql_values(witness_get(
        &root,
        "apm_config.obfuscation.opensearch.obfuscate_sql_values",
    ));
    consumer.consume_apm_config_obfuscation_redis_enabled(witness_get(&root, "apm_config.obfuscation.redis.enabled"));
    consumer.consume_apm_config_obfuscation_redis_remove_all_args(witness_get(
        &root,
        "apm_config.obfuscation.redis.remove_all_args",
    ));
    consumer.consume_apm_config_obfuscation_valkey_enabled(witness_get(&root, "apm_config.obfuscation.valkey.enabled"));
    consumer.consume_apm_config_obfuscation_valkey_remove_all_args(witness_get(
        &root,
        "apm_config.obfuscation.valkey.remove_all_args",
    ));
    consumer.consume_bind_host(witness_get(&root, "bind_host"));
    consumer.consume_cmd_port(witness_get(&root, "cmd_port"));
    consumer.consume_cri_connection_timeout(witness_get(&root, "cri_connection_timeout"));
    consumer.consume_cri_query_timeout(witness_get(&root, "cri_query_timeout"));
    consumer.consume_data_plane_api_listen_address(witness_get(&root, "data_plane.api_listen_address"));
    consumer.consume_data_plane_dogstatsd_aggregator_tag_filter_cache_capacity(witness_get(
        &root,
        "data_plane.dogstatsd.aggregator_tag_filter_cache_capacity",
    ));
    consumer.consume_data_plane_log_file(witness_get(&root, "data_plane.log_file"));
    consumer.consume_data_plane_otlp_proxy_logs_enabled(witness_get(&root, "data_plane.otlp.proxy.logs.enabled"));
    consumer.consume_data_plane_otlp_proxy_metrics_enabled(witness_get(&root, "data_plane.otlp.proxy.metrics.enabled"));
    consumer.consume_data_plane_otlp_proxy_traces_enabled(witness_get(&root, "data_plane.otlp.proxy.traces.enabled"));
    consumer.consume_data_plane_remote_agent_enabled(witness_get(&root, "data_plane.remote_agent_enabled"));
    consumer.consume_data_plane_secure_api_listen_address(witness_get(&root, "data_plane.secure_api_listen_address"));
    consumer.consume_data_plane_use_new_config_stream_endpoint(witness_get(
        &root,
        "data_plane.use_new_config_stream_endpoint",
    ));
    consumer.consume_dd_url(witness_get(&root, "dd_url"));
    consumer.consume_dogstatsd_buffer_size(witness_get(&root, "dogstatsd_buffer_size"));
    consumer.consume_dogstatsd_capture_depth(witness_get(&root, "dogstatsd_capture_depth"));
    consumer.consume_dogstatsd_capture_path(witness_get(&root, "dogstatsd_capture_path"));
    consumer.consume_dogstatsd_context_expiry_seconds(witness_get(&root, "dogstatsd_context_expiry_seconds"));
    consumer.consume_dogstatsd_entity_id_precedence(witness_get(&root, "dogstatsd_entity_id_precedence"));
    consumer.consume_dogstatsd_eol_required(witness_get(&root, "dogstatsd_eol_required"));
    consumer.consume_dogstatsd_flush_incomplete_buckets(witness_get(&root, "dogstatsd_flush_incomplete_buckets"));
    consumer.consume_dogstatsd_log_file(witness_get(&root, "dogstatsd_log_file"));
    consumer.consume_dogstatsd_log_file_max_rolls(witness_get(&root, "dogstatsd_log_file_max_rolls"));
    consumer.consume_dogstatsd_log_file_max_size(witness_get(&root, "dogstatsd_log_file_max_size"));
    consumer.consume_dogstatsd_logging_enabled(witness_get(&root, "dogstatsd_logging_enabled"));
    consumer.consume_dogstatsd_mapper_cache_size(witness_get(&root, "dogstatsd_mapper_cache_size"));
    consumer.consume_dogstatsd_mapper_profiles(witness_get(&root, "dogstatsd_mapper_profiles"));
    consumer.consume_dogstatsd_metrics_stats_enable(witness_get(&root, "dogstatsd_metrics_stats_enable"));
    consumer.consume_dogstatsd_no_aggregation_pipeline(witness_get(&root, "dogstatsd_no_aggregation_pipeline"));
    consumer.consume_dogstatsd_non_local_traffic(witness_get(&root, "dogstatsd_non_local_traffic"));
    consumer.consume_dogstatsd_origin_detection(witness_get(&root, "dogstatsd_origin_detection"));
    consumer.consume_dogstatsd_origin_detection_client(witness_get(&root, "dogstatsd_origin_detection_client"));
    consumer.consume_dogstatsd_origin_optout_enabled(witness_get(&root, "dogstatsd_origin_optout_enabled"));
    consumer.consume_dogstatsd_port(witness_get(&root, "dogstatsd_port"));
    consumer.consume_dogstatsd_so_rcvbuf(witness_get(&root, "dogstatsd_so_rcvbuf"));
    consumer.consume_dogstatsd_socket(witness_get(&root, "dogstatsd_socket"));
    consumer.consume_dogstatsd_stream_log_too_big(witness_get(&root, "dogstatsd_stream_log_too_big"));
    consumer.consume_dogstatsd_stream_socket(witness_get(&root, "dogstatsd_stream_socket"));
    consumer.consume_dogstatsd_string_interner_size(witness_get(&root, "dogstatsd_string_interner_size"));
    consumer.consume_dogstatsd_tag_cardinality(witness_get(&root, "dogstatsd_tag_cardinality"));
    consumer.consume_dogstatsd_tags(witness_get(&root, "dogstatsd_tags"));
    consumer.consume_enable_payloads_events(witness_get(&root, "enable_payloads.events"));
    consumer.consume_enable_payloads_series(witness_get(&root, "enable_payloads.series"));
    consumer.consume_enable_payloads_service_checks(witness_get(&root, "enable_payloads.service_checks"));
    consumer.consume_enable_payloads_sketches(witness_get(&root, "enable_payloads.sketches"));
    consumer.consume_env(witness_get(&root, "env"));
    consumer.consume_forwarder_apikey_validation_interval(witness_get(&root, "forwarder_apikey_validation_interval"));
    consumer.consume_forwarder_backoff_base(witness_get(&root, "forwarder_backoff_base"));
    consumer.consume_forwarder_backoff_factor(witness_get(&root, "forwarder_backoff_factor"));
    consumer.consume_forwarder_backoff_max(witness_get(&root, "forwarder_backoff_max"));
    consumer.consume_forwarder_connection_reset_interval(witness_get(&root, "forwarder_connection_reset_interval"));
    consumer.consume_forwarder_high_prio_buffer_size(witness_get(&root, "forwarder_high_prio_buffer_size"));
    consumer.consume_forwarder_http_protocol(witness_get(&root, "forwarder_http_protocol"));
    consumer.consume_forwarder_max_concurrent_requests(witness_get(&root, "forwarder_max_concurrent_requests"));
    consumer.consume_forwarder_num_workers(witness_get(&root, "forwarder_num_workers"));
    consumer.consume_forwarder_outdated_file_in_days(witness_get(&root, "forwarder_outdated_file_in_days"));
    consumer.consume_forwarder_recovery_interval(witness_get(&root, "forwarder_recovery_interval"));
    consumer.consume_forwarder_recovery_reset(witness_get(&root, "forwarder_recovery_reset"));
    consumer.consume_forwarder_retry_queue_capacity_time_interval_sec(witness_get(
        &root,
        "forwarder_retry_queue_capacity_time_interval_sec",
    ));
    consumer.consume_forwarder_retry_queue_max_size(witness_get(&root, "forwarder_retry_queue_max_size"));
    consumer
        .consume_forwarder_retry_queue_payloads_max_size(witness_get(&root, "forwarder_retry_queue_payloads_max_size"));
    consumer.consume_forwarder_storage_max_disk_ratio(witness_get(&root, "forwarder_storage_max_disk_ratio"));
    consumer.consume_forwarder_storage_max_size_in_bytes(witness_get(&root, "forwarder_storage_max_size_in_bytes"));
    consumer.consume_forwarder_storage_path(witness_get(&root, "forwarder_storage_path"));
    consumer.consume_forwarder_timeout(witness_get(&root, "forwarder_timeout"));
    consumer.consume_histogram_aggregates(witness_get(&root, "histogram_aggregates"));
    consumer.consume_histogram_copy_to_distribution(witness_get(&root, "histogram_copy_to_distribution"));
    consumer.consume_histogram_copy_to_distribution_prefix(witness_get(&root, "histogram_copy_to_distribution_prefix"));
    consumer.consume_log_format_rfc3339(witness_get(&root, "log_format_rfc3339"));
    consumer.consume_log_level(witness_get(&root, "log_level"));
    consumer.consume_log_payloads(witness_get(&root, "log_payloads"));
    consumer.consume_metric_filterlist(witness_get(&root, "metric_filterlist"));
    consumer.consume_metric_filterlist_match_prefix(witness_get(&root, "metric_filterlist_match_prefix"));
    consumer.consume_min_tls_version(witness_get(&root, "min_tls_version"));
    consumer.consume_multi_region_failover_api_key(witness_get(&root, "multi_region_failover.api_key"));
    consumer.consume_multi_region_failover_dd_url(witness_get(&root, "multi_region_failover.dd_url"));
    consumer.consume_multi_region_failover_enabled(witness_get(&root, "multi_region_failover.enabled"));
    consumer
        .consume_multi_region_failover_failover_metrics(witness_get(&root, "multi_region_failover.failover_metrics"));
    consumer
        .consume_multi_region_failover_metric_allowlist(witness_get(&root, "multi_region_failover.metric_allowlist"));
    consumer.consume_multi_region_failover_site(witness_get(&root, "multi_region_failover.site"));
    consumer.consume_no_proxy_nonexact_match(witness_get(&root, "no_proxy_nonexact_match"));
    consumer.consume_observability_pipelines_worker_metrics_enabled(witness_get(
        &root,
        "observability_pipelines_worker.metrics.enabled",
    ));
    consumer.consume_observability_pipelines_worker_metrics_url(witness_get(
        &root,
        "observability_pipelines_worker.metrics.url",
    ));
    consumer.consume_origin_detection_unified(witness_get(&root, "origin_detection_unified"));
    consumer.consume_otlp_config_logs_enabled(witness_get(&root, "otlp_config.logs.enabled"));
    consumer.consume_otlp_config_metrics_enabled(witness_get(&root, "otlp_config.metrics.enabled"));
    consumer.consume_otlp_config_receiver_protocols_grpc_endpoint(witness_get(
        &root,
        "otlp_config.receiver.protocols.grpc.endpoint",
    ));
    consumer.consume_otlp_config_receiver_protocols_grpc_max_recv_msg_size_mib(witness_get(
        &root,
        "otlp_config.receiver.protocols.grpc.max_recv_msg_size_mib",
    ));
    consumer.consume_otlp_config_receiver_protocols_grpc_transport(witness_get(
        &root,
        "otlp_config.receiver.protocols.grpc.transport",
    ));
    consumer.consume_otlp_config_receiver_protocols_http_endpoint(witness_get(
        &root,
        "otlp_config.receiver.protocols.http.endpoint",
    ));
    consumer.consume_otlp_config_traces_enabled(witness_get(&root, "otlp_config.traces.enabled"));
    consumer.consume_otlp_config_traces_internal_port(witness_get(&root, "otlp_config.traces.internal_port"));
    consumer.consume_otlp_config_traces_probabilistic_sampler_sampling_percentage(witness_get(
        &root,
        "otlp_config.traces.probabilistic_sampler.sampling_percentage",
    ));
    consumer.consume_provider_kind(witness_get(&root, "provider_kind"));
    consumer.consume_proxy_http(witness_get(&root, "proxy.http"));
    consumer.consume_proxy_https(witness_get(&root, "proxy.https"));
    consumer.consume_proxy_no_proxy(witness_get(&root, "proxy.no_proxy"));
    consumer.consume_secret_backend_command(witness_get(&root, "secret_backend_command"));
    consumer.consume_secret_refresh_on_api_key_failure_interval(witness_get(
        &root,
        "secret_refresh_on_api_key_failure_interval",
    ));
    consumer.consume_serializer_compressor_kind(witness_get(&root, "serializer_compressor_kind"));
    consumer.consume_serializer_max_payload_size(witness_get(&root, "serializer_max_payload_size"));
    consumer.consume_serializer_max_series_payload_size(witness_get(&root, "serializer_max_series_payload_size"));
    consumer.consume_serializer_max_series_points_per_payload(witness_get(
        &root,
        "serializer_max_series_points_per_payload",
    ));
    consumer.consume_serializer_max_series_uncompressed_payload_size(witness_get(
        &root,
        "serializer_max_series_uncompressed_payload_size",
    ));
    consumer.consume_serializer_max_uncompressed_payload_size(witness_get(
        &root,
        "serializer_max_uncompressed_payload_size",
    ));
    consumer.consume_serializer_zstd_compressor_level(witness_get(&root, "serializer_zstd_compressor_level"));
    consumer.consume_site(witness_get(&root, "site"));
    consumer.consume_skip_ssl_validation(witness_get(&root, "skip_ssl_validation"));
    consumer.consume_sslkeylogfile(witness_get(&root, "sslkeylogfile"));
    consumer.consume_statsd_forward_host(witness_get(&root, "statsd_forward_host"));
    consumer.consume_statsd_forward_port(witness_get(&root, "statsd_forward_port"));
    consumer.consume_statsd_metric_blocklist(witness_get(&root, "statsd_metric_blocklist"));
    consumer.consume_statsd_metric_blocklist_match_prefix(witness_get(&root, "statsd_metric_blocklist_match_prefix"));
    consumer.consume_statsd_metric_namespace(witness_get(&root, "statsd_metric_namespace"));
    consumer.consume_statsd_metric_namespace_blacklist(witness_get(&root, "statsd_metric_namespace_blacklist"));
    consumer.consume_syslog_rfc(witness_get(&root, "syslog_rfc"));
    consumer.consume_syslog_uri(witness_get(&root, "syslog_uri"));
    consumer.consume_use_proxy_for_cloud_metadata(witness_get(&root, "use_proxy_for_cloud_metadata"));
    consumer.consume_use_v2_api_series(witness_get(&root, "use_v2_api.series"));
    consumer.consume_vector_metrics_enabled(witness_get(&root, "vector.metrics.enabled"));
    consumer.consume_vector_metrics_url(witness_get(&root, "vector.metrics.url"));
    consumer.consume_vsock_addr(witness_get(&root, "vsock_addr"));
}

/// Navigate `root` by the dotted `path` and deserialize the value into `T`.
///
/// A missing or null value yields `T::default()`. A value that fails to deserialize also yields the
/// default; the generated value types are chosen to match the serialized representation, so this only
/// trips on genuinely malformed input.
fn witness_get<T: DeserializeOwned + Default>(root: &serde_json::Value, path: &str) -> T {
    let mut cur = root;
    for part in path.split('.') {
        match cur.get(part) {
            Some(value) => cur = value,
            None => return T::default(),
        }
    }
    if cur.is_null() {
        return T::default();
    }
    serde_json::from_value(cur.clone()).unwrap_or_default()
}
