// @generated by build.rs from core_schema.yaml + schema_overlay.yaml — DO NOT EDIT
// Regenerate by running `cargo build -p datadog-agent-config`.
#![allow(clippy::all, dead_code, unused)]

use std::collections::HashMap;

use crate::datadog_configuration::*;
use crate::DatadogConfiguration;

/// Witness over every supported Datadog configuration key.
///
/// One method per `support: full` / `support: partial` overlay leaf. A type that implements
/// this trait is forced by the compiler to decide a destination for every supported key: adding
/// or removing a key changes the trait and breaks the implementation until it is handled.
pub trait DatadogConfigConsumer {
    /// Consume `additional_endpoints`.
    fn consume_additional_endpoints(&mut self, value: HashMap<String, Vec<String>>);
    /// Consume `allow_arbitrary_tags`.
    fn consume_allow_arbitrary_tags(&mut self, value: bool);
    /// Consume `api_key`.
    fn consume_api_key(&mut self, value: String);
    /// Consume `apm_config.obfuscation.credit_cards.enabled`.
    fn consume_apm_config_obfuscation_credit_cards_enabled(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.credit_cards.keep_values`.
    fn consume_apm_config_obfuscation_credit_cards_keep_values(&mut self, value: Vec<String>);
    /// Consume `apm_config.obfuscation.credit_cards.luhn`.
    fn consume_apm_config_obfuscation_credit_cards_luhn(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.elasticsearch.enabled`.
    fn consume_apm_config_obfuscation_elasticsearch_enabled(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.elasticsearch.keep_values`.
    fn consume_apm_config_obfuscation_elasticsearch_keep_values(&mut self, value: Vec<String>);
    /// Consume `apm_config.obfuscation.elasticsearch.obfuscate_sql_values`.
    fn consume_apm_config_obfuscation_elasticsearch_obfuscate_sql_values(&mut self, value: Vec<String>);
    /// Consume `apm_config.obfuscation.http.remove_paths_with_digits`.
    fn consume_apm_config_obfuscation_http_remove_paths_with_digits(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.http.remove_query_string`.
    fn consume_apm_config_obfuscation_http_remove_query_string(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.memcached.enabled`.
    fn consume_apm_config_obfuscation_memcached_enabled(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.memcached.keep_command`.
    fn consume_apm_config_obfuscation_memcached_keep_command(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.mongodb.enabled`.
    fn consume_apm_config_obfuscation_mongodb_enabled(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.mongodb.keep_values`.
    fn consume_apm_config_obfuscation_mongodb_keep_values(&mut self, value: Vec<String>);
    /// Consume `apm_config.obfuscation.mongodb.obfuscate_sql_values`.
    fn consume_apm_config_obfuscation_mongodb_obfuscate_sql_values(&mut self, value: Vec<String>);
    /// Consume `apm_config.obfuscation.opensearch.enabled`.
    fn consume_apm_config_obfuscation_opensearch_enabled(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.opensearch.keep_values`.
    fn consume_apm_config_obfuscation_opensearch_keep_values(&mut self, value: Vec<String>);
    /// Consume `apm_config.obfuscation.opensearch.obfuscate_sql_values`.
    fn consume_apm_config_obfuscation_opensearch_obfuscate_sql_values(&mut self, value: Vec<String>);
    /// Consume `apm_config.obfuscation.redis.enabled`.
    fn consume_apm_config_obfuscation_redis_enabled(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.redis.remove_all_args`.
    fn consume_apm_config_obfuscation_redis_remove_all_args(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.valkey.enabled`.
    fn consume_apm_config_obfuscation_valkey_enabled(&mut self, value: bool);
    /// Consume `apm_config.obfuscation.valkey.remove_all_args`.
    fn consume_apm_config_obfuscation_valkey_remove_all_args(&mut self, value: bool);
    /// Consume `bind_host`.
    fn consume_bind_host(&mut self, value: Option<::serde_json::Value>);
    /// Consume `cmd_port`.
    fn consume_cmd_port(&mut self, value: f64);
    /// Consume `cri_connection_timeout`.
    fn consume_cri_connection_timeout(&mut self, value: f64);
    /// Consume `cri_query_timeout`.
    fn consume_cri_query_timeout(&mut self, value: f64);
    /// Consume `data_plane.dogstatsd.aggregator_tag_filter_cache_capacity`.
    fn consume_data_plane_dogstatsd_aggregator_tag_filter_cache_capacity(&mut self, value: f64);
    /// Consume `dd_url`.
    fn consume_dd_url(&mut self, value: Option<::serde_json::Value>);
    /// Consume `dogstatsd_buffer_size`.
    fn consume_dogstatsd_buffer_size(&mut self, value: f64);
    /// Consume `dogstatsd_capture_depth`.
    fn consume_dogstatsd_capture_depth(&mut self, value: f64);
    /// Consume `dogstatsd_capture_path`.
    fn consume_dogstatsd_capture_path(&mut self, value: String);
    /// Consume `dogstatsd_context_expiry_seconds`.
    fn consume_dogstatsd_context_expiry_seconds(&mut self, value: f64);
    /// Consume `dogstatsd_entity_id_precedence`.
    fn consume_dogstatsd_entity_id_precedence(&mut self, value: bool);
    /// Consume `dogstatsd_eol_required`.
    fn consume_dogstatsd_eol_required(&mut self, value: Vec<String>);
    /// Consume `dogstatsd_flush_incomplete_buckets`.
    fn consume_dogstatsd_flush_incomplete_buckets(&mut self, value: bool);
    /// Consume `dogstatsd_log_file`.
    fn consume_dogstatsd_log_file(&mut self, value: String);
    /// Consume `dogstatsd_log_file_max_rolls`.
    fn consume_dogstatsd_log_file_max_rolls(&mut self, value: f64);
    /// Consume `dogstatsd_log_file_max_size`.
    fn consume_dogstatsd_log_file_max_size(&mut self, value: String);
    /// Consume `dogstatsd_logging_enabled`.
    fn consume_dogstatsd_logging_enabled(&mut self, value: bool);
    /// Consume `dogstatsd_mapper_cache_size`.
    fn consume_dogstatsd_mapper_cache_size(&mut self, value: f64);
    /// Consume `dogstatsd_mapper_profiles`.
    fn consume_dogstatsd_mapper_profiles(&mut self, value: Option<::serde_json::Value>);
    /// Consume `dogstatsd_metrics_stats_enable`.
    fn consume_dogstatsd_metrics_stats_enable(&mut self, value: bool);
    /// Consume `dogstatsd_no_aggregation_pipeline`.
    fn consume_dogstatsd_no_aggregation_pipeline(&mut self, value: bool);
    /// Consume `dogstatsd_non_local_traffic`.
    fn consume_dogstatsd_non_local_traffic(&mut self, value: bool);
    /// Consume `dogstatsd_origin_detection`.
    fn consume_dogstatsd_origin_detection(&mut self, value: bool);
    /// Consume `dogstatsd_origin_detection_client`.
    fn consume_dogstatsd_origin_detection_client(&mut self, value: bool);
    /// Consume `dogstatsd_origin_optout_enabled`.
    fn consume_dogstatsd_origin_optout_enabled(&mut self, value: bool);
    /// Consume `dogstatsd_port`.
    fn consume_dogstatsd_port(&mut self, value: f64);
    /// Consume `dogstatsd_so_rcvbuf`.
    fn consume_dogstatsd_so_rcvbuf(&mut self, value: f64);
    /// Consume `dogstatsd_socket`.
    fn consume_dogstatsd_socket(&mut self, value: Option<String>);
    /// Consume `dogstatsd_stream_log_too_big`.
    fn consume_dogstatsd_stream_log_too_big(&mut self, value: bool);
    /// Consume `dogstatsd_stream_socket`.
    fn consume_dogstatsd_stream_socket(&mut self, value: String);
    /// Consume `dogstatsd_string_interner_size`.
    fn consume_dogstatsd_string_interner_size(&mut self, value: f64);
    /// Consume `dogstatsd_tag_cardinality`.
    fn consume_dogstatsd_tag_cardinality(&mut self, value: String);
    /// Consume `dogstatsd_tags`.
    fn consume_dogstatsd_tags(&mut self, value: Vec<String>);
    /// Consume `enable_payloads.events`.
    fn consume_enable_payloads_events(&mut self, value: bool);
    /// Consume `enable_payloads.series`.
    fn consume_enable_payloads_series(&mut self, value: bool);
    /// Consume `enable_payloads.service_checks`.
    fn consume_enable_payloads_service_checks(&mut self, value: bool);
    /// Consume `enable_payloads.sketches`.
    fn consume_enable_payloads_sketches(&mut self, value: bool);
    /// Consume `env`.
    fn consume_env(&mut self, value: String);
    /// Consume `forwarder_backoff_base`.
    fn consume_forwarder_backoff_base(&mut self, value: f64);
    /// Consume `forwarder_backoff_factor`.
    fn consume_forwarder_backoff_factor(&mut self, value: f64);
    /// Consume `forwarder_backoff_max`.
    fn consume_forwarder_backoff_max(&mut self, value: f64);
    /// Consume `forwarder_connection_reset_interval`.
    fn consume_forwarder_connection_reset_interval(&mut self, value: f64);
    /// Consume `forwarder_high_prio_buffer_size`.
    fn consume_forwarder_high_prio_buffer_size(&mut self, value: f64);
    /// Consume `forwarder_http_protocol`.
    fn consume_forwarder_http_protocol(&mut self, value: String);
    /// Consume `forwarder_max_concurrent_requests`.
    fn consume_forwarder_max_concurrent_requests(&mut self, value: f64);
    /// Consume `forwarder_num_workers`.
    fn consume_forwarder_num_workers(&mut self, value: f64);
    /// Consume `forwarder_outdated_file_in_days`.
    fn consume_forwarder_outdated_file_in_days(&mut self, value: f64);
    /// Consume `forwarder_recovery_interval`.
    fn consume_forwarder_recovery_interval(&mut self, value: f64);
    /// Consume `forwarder_recovery_reset`.
    fn consume_forwarder_recovery_reset(&mut self, value: bool);
    /// Consume `forwarder_retry_queue_max_size`.
    fn consume_forwarder_retry_queue_max_size(&mut self, value: f64);
    /// Consume `forwarder_retry_queue_payloads_max_size`.
    fn consume_forwarder_retry_queue_payloads_max_size(&mut self, value: f64);
    /// Consume `forwarder_storage_max_disk_ratio`.
    fn consume_forwarder_storage_max_disk_ratio(&mut self, value: f64);
    /// Consume `forwarder_storage_max_size_in_bytes`.
    fn consume_forwarder_storage_max_size_in_bytes(&mut self, value: f64);
    /// Consume `forwarder_storage_path`.
    fn consume_forwarder_storage_path(&mut self, value: String);
    /// Consume `forwarder_timeout`.
    fn consume_forwarder_timeout(&mut self, value: f64);
    /// Consume `histogram_aggregates`.
    fn consume_histogram_aggregates(&mut self, value: Vec<String>);
    /// Consume `histogram_copy_to_distribution`.
    fn consume_histogram_copy_to_distribution(&mut self, value: bool);
    /// Consume `histogram_copy_to_distribution_prefix`.
    fn consume_histogram_copy_to_distribution_prefix(&mut self, value: String);
    /// Consume `log_format_rfc3339`.
    fn consume_log_format_rfc3339(&mut self, value: bool);
    /// Consume `log_level`.
    fn consume_log_level(&mut self, value: String);
    /// Consume `log_payloads`.
    fn consume_log_payloads(&mut self, value: bool);
    /// Consume `metric_filterlist`.
    fn consume_metric_filterlist(&mut self, value: Vec<String>);
    /// Consume `metric_filterlist_match_prefix`.
    fn consume_metric_filterlist_match_prefix(&mut self, value: bool);
    /// Consume `min_tls_version`.
    fn consume_min_tls_version(&mut self, value: String);
    /// Consume `multi_region_failover.api_key`.
    fn consume_multi_region_failover_api_key(&mut self, value: Option<::serde_json::Value>);
    /// Consume `multi_region_failover.dd_url`.
    fn consume_multi_region_failover_dd_url(&mut self, value: Option<::serde_json::Value>);
    /// Consume `multi_region_failover.enabled`.
    fn consume_multi_region_failover_enabled(&mut self, value: bool);
    /// Consume `multi_region_failover.failover_metrics`.
    fn consume_multi_region_failover_failover_metrics(&mut self, value: bool);
    /// Consume `multi_region_failover.metric_allowlist`.
    fn consume_multi_region_failover_metric_allowlist(&mut self, value: Option<::serde_json::Value>);
    /// Consume `multi_region_failover.site`.
    fn consume_multi_region_failover_site(&mut self, value: Option<::serde_json::Value>);
    /// Consume `no_proxy_nonexact_match`.
    fn consume_no_proxy_nonexact_match(&mut self, value: bool);
    /// Consume `observability_pipelines_worker.metrics.enabled`.
    fn consume_observability_pipelines_worker_metrics_enabled(&mut self, value: bool);
    /// Consume `observability_pipelines_worker.metrics.url`.
    fn consume_observability_pipelines_worker_metrics_url(&mut self, value: String);
    /// Consume `origin_detection_unified`.
    fn consume_origin_detection_unified(&mut self, value: bool);
    /// Consume `otlp_config.logs.enabled`.
    fn consume_otlp_config_logs_enabled(&mut self, value: bool);
    /// Consume `otlp_config.metrics.enabled`.
    fn consume_otlp_config_metrics_enabled(&mut self, value: bool);
    /// Consume `otlp_config.receiver.protocols.grpc.endpoint`.
    fn consume_otlp_config_receiver_protocols_grpc_endpoint(&mut self, value: String);
    /// Consume `otlp_config.receiver.protocols.grpc.max_recv_msg_size_mib`.
    fn consume_otlp_config_receiver_protocols_grpc_max_recv_msg_size_mib(&mut self, value: f64);
    /// Consume `otlp_config.receiver.protocols.grpc.transport`.
    fn consume_otlp_config_receiver_protocols_grpc_transport(&mut self, value: String);
    /// Consume `otlp_config.receiver.protocols.http.endpoint`.
    fn consume_otlp_config_receiver_protocols_http_endpoint(&mut self, value: String);
    /// Consume `otlp_config.traces.enabled`.
    fn consume_otlp_config_traces_enabled(&mut self, value: bool);
    /// Consume `otlp_config.traces.internal_port`.
    fn consume_otlp_config_traces_internal_port(&mut self, value: f64);
    /// Consume `otlp_config.traces.probabilistic_sampler.sampling_percentage`.
    fn consume_otlp_config_traces_probabilistic_sampler_sampling_percentage(&mut self, value: f64);
    /// Consume `provider_kind`.
    fn consume_provider_kind(&mut self, value: Option<::serde_json::Value>);
    /// Consume `proxy.http`.
    fn consume_proxy_http(&mut self, value: String);
    /// Consume `proxy.https`.
    fn consume_proxy_https(&mut self, value: String);
    /// Consume `proxy.no_proxy`.
    fn consume_proxy_no_proxy(&mut self, value: Vec<String>);
    /// Consume `serializer_compressor_kind`.
    fn consume_serializer_compressor_kind(&mut self, value: String);
    /// Consume `serializer_max_payload_size`.
    fn consume_serializer_max_payload_size(&mut self, value: f64);
    /// Consume `serializer_max_series_payload_size`.
    fn consume_serializer_max_series_payload_size(&mut self, value: f64);
    /// Consume `serializer_max_series_points_per_payload`.
    fn consume_serializer_max_series_points_per_payload(&mut self, value: f64);
    /// Consume `serializer_max_series_uncompressed_payload_size`.
    fn consume_serializer_max_series_uncompressed_payload_size(&mut self, value: f64);
    /// Consume `serializer_max_uncompressed_payload_size`.
    fn consume_serializer_max_uncompressed_payload_size(&mut self, value: f64);
    /// Consume `serializer_zstd_compressor_level`.
    fn consume_serializer_zstd_compressor_level(&mut self, value: f64);
    /// Consume `site`.
    fn consume_site(&mut self, value: Option<::serde_json::Value>);
    /// Consume `skip_ssl_validation`.
    fn consume_skip_ssl_validation(&mut self, value: bool);
    /// Consume `statsd_forward_host`.
    fn consume_statsd_forward_host(&mut self, value: String);
    /// Consume `statsd_forward_port`.
    fn consume_statsd_forward_port(&mut self, value: f64);
    /// Consume `statsd_metric_blocklist`.
    fn consume_statsd_metric_blocklist(&mut self, value: Vec<String>);
    /// Consume `statsd_metric_blocklist_match_prefix`.
    fn consume_statsd_metric_blocklist_match_prefix(&mut self, value: bool);
    /// Consume `statsd_metric_namespace`.
    fn consume_statsd_metric_namespace(&mut self, value: String);
    /// Consume `statsd_metric_namespace_blacklist`.
    fn consume_statsd_metric_namespace_blacklist(&mut self, value: Vec<String>);
    /// Consume `syslog_rfc`.
    fn consume_syslog_rfc(&mut self, value: bool);
    /// Consume `syslog_uri`.
    fn consume_syslog_uri(&mut self, value: String);
    /// Consume `use_proxy_for_cloud_metadata`.
    fn consume_use_proxy_for_cloud_metadata(&mut self, value: bool);
    /// Consume `use_v2_api.series`.
    fn consume_use_v2_api_series(&mut self, value: bool);
    /// Consume `vector.metrics.enabled`.
    fn consume_vector_metrics_enabled(&mut self, value: bool);
    /// Consume `vector.metrics.url`.
    fn consume_vector_metrics_url(&mut self, value: String);
    /// Consume `vsock_addr`.
    fn consume_vsock_addr(&mut self, value: String);
}

/// Feed every supported key's already-defaulted value into `consumer`.
///
/// Absent sections resolve to their schema defaults via `unwrap_or_default()` chains (every
/// generated section struct threads the schema default functions through its `Default` impl), so
/// the consumer always receives a concrete, defaulted value.
pub fn drive(config: &DatadogConfiguration, consumer: &mut impl DatadogConfigConsumer) {
    consumer.consume_additional_endpoints(config.additional_endpoints.clone());
    consumer.consume_allow_arbitrary_tags(config.allow_arbitrary_tags);
    consumer.consume_api_key(config.api_key.clone());
    consumer.consume_apm_config_obfuscation_credit_cards_enabled(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .credit_cards
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_apm_config_obfuscation_credit_cards_keep_values(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .credit_cards
            .clone()
            .unwrap_or_default()
            .keep_values
            .clone(),
    );
    consumer.consume_apm_config_obfuscation_credit_cards_luhn(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .credit_cards
            .clone()
            .unwrap_or_default()
            .luhn,
    );
    consumer.consume_apm_config_obfuscation_elasticsearch_enabled(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .elasticsearch
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_apm_config_obfuscation_elasticsearch_keep_values(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .elasticsearch
            .clone()
            .unwrap_or_default()
            .keep_values
            .clone(),
    );
    consumer.consume_apm_config_obfuscation_elasticsearch_obfuscate_sql_values(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .elasticsearch
            .clone()
            .unwrap_or_default()
            .obfuscate_sql_values
            .clone(),
    );
    consumer.consume_apm_config_obfuscation_http_remove_paths_with_digits(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .http
            .clone()
            .unwrap_or_default()
            .remove_paths_with_digits,
    );
    consumer.consume_apm_config_obfuscation_http_remove_query_string(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .http
            .clone()
            .unwrap_or_default()
            .remove_query_string,
    );
    consumer.consume_apm_config_obfuscation_memcached_enabled(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .memcached
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_apm_config_obfuscation_memcached_keep_command(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .memcached
            .clone()
            .unwrap_or_default()
            .keep_command,
    );
    consumer.consume_apm_config_obfuscation_mongodb_enabled(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .mongodb
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_apm_config_obfuscation_mongodb_keep_values(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .mongodb
            .clone()
            .unwrap_or_default()
            .keep_values
            .clone(),
    );
    consumer.consume_apm_config_obfuscation_mongodb_obfuscate_sql_values(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .mongodb
            .clone()
            .unwrap_or_default()
            .obfuscate_sql_values
            .clone(),
    );
    consumer.consume_apm_config_obfuscation_opensearch_enabled(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .opensearch
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_apm_config_obfuscation_opensearch_keep_values(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .opensearch
            .clone()
            .unwrap_or_default()
            .keep_values
            .clone(),
    );
    consumer.consume_apm_config_obfuscation_opensearch_obfuscate_sql_values(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .opensearch
            .clone()
            .unwrap_or_default()
            .obfuscate_sql_values
            .clone(),
    );
    consumer.consume_apm_config_obfuscation_redis_enabled(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .redis
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_apm_config_obfuscation_redis_remove_all_args(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .redis
            .clone()
            .unwrap_or_default()
            .remove_all_args,
    );
    consumer.consume_apm_config_obfuscation_valkey_enabled(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .valkey
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_apm_config_obfuscation_valkey_remove_all_args(
        config
            .apm_config
            .clone()
            .unwrap_or_default()
            .obfuscation
            .clone()
            .unwrap_or_default()
            .valkey
            .clone()
            .unwrap_or_default()
            .remove_all_args,
    );
    consumer.consume_bind_host(config.bind_host.clone());
    consumer.consume_cmd_port(config.cmd_port);
    consumer.consume_cri_connection_timeout(config.cri_connection_timeout);
    consumer.consume_cri_query_timeout(config.cri_query_timeout);
    consumer.consume_data_plane_dogstatsd_aggregator_tag_filter_cache_capacity(
        config
            .data_plane
            .clone()
            .unwrap_or_default()
            .dogstatsd
            .clone()
            .unwrap_or_default()
            .aggregator_tag_filter_cache_capacity,
    );
    consumer.consume_dd_url(config.dd_url.clone());
    consumer.consume_dogstatsd_buffer_size(config.dogstatsd_buffer_size);
    consumer.consume_dogstatsd_capture_depth(config.dogstatsd_capture_depth);
    consumer.consume_dogstatsd_capture_path(config.dogstatsd_capture_path.clone());
    consumer.consume_dogstatsd_context_expiry_seconds(config.dogstatsd_context_expiry_seconds);
    consumer.consume_dogstatsd_entity_id_precedence(config.dogstatsd_entity_id_precedence);
    consumer.consume_dogstatsd_eol_required(config.dogstatsd_eol_required.clone());
    consumer.consume_dogstatsd_flush_incomplete_buckets(config.dogstatsd_flush_incomplete_buckets);
    consumer.consume_dogstatsd_log_file(config.dogstatsd_log_file.clone());
    consumer.consume_dogstatsd_log_file_max_rolls(config.dogstatsd_log_file_max_rolls);
    consumer.consume_dogstatsd_log_file_max_size(config.dogstatsd_log_file_max_size.clone());
    consumer.consume_dogstatsd_logging_enabled(config.dogstatsd_logging_enabled);
    consumer.consume_dogstatsd_mapper_cache_size(config.dogstatsd_mapper_cache_size);
    consumer.consume_dogstatsd_mapper_profiles(config.dogstatsd_mapper_profiles.clone());
    consumer.consume_dogstatsd_metrics_stats_enable(config.dogstatsd_metrics_stats_enable);
    consumer.consume_dogstatsd_no_aggregation_pipeline(config.dogstatsd_no_aggregation_pipeline);
    consumer.consume_dogstatsd_non_local_traffic(config.dogstatsd_non_local_traffic);
    consumer.consume_dogstatsd_origin_detection(config.dogstatsd_origin_detection);
    consumer.consume_dogstatsd_origin_detection_client(config.dogstatsd_origin_detection_client);
    consumer.consume_dogstatsd_origin_optout_enabled(config.dogstatsd_origin_optout_enabled);
    consumer.consume_dogstatsd_port(config.dogstatsd_port);
    consumer.consume_dogstatsd_so_rcvbuf(config.dogstatsd_so_rcvbuf);
    consumer.consume_dogstatsd_socket(config.dogstatsd_socket.clone());
    consumer.consume_dogstatsd_stream_log_too_big(config.dogstatsd_stream_log_too_big);
    consumer.consume_dogstatsd_stream_socket(config.dogstatsd_stream_socket.clone());
    consumer.consume_dogstatsd_string_interner_size(config.dogstatsd_string_interner_size);
    consumer.consume_dogstatsd_tag_cardinality(config.dogstatsd_tag_cardinality.clone());
    consumer.consume_dogstatsd_tags(config.dogstatsd_tags.clone());
    consumer.consume_enable_payloads_events(config.enable_payloads.clone().unwrap_or_default().events);
    consumer.consume_enable_payloads_series(config.enable_payloads.clone().unwrap_or_default().series);
    consumer.consume_enable_payloads_service_checks(config.enable_payloads.clone().unwrap_or_default().service_checks);
    consumer.consume_enable_payloads_sketches(config.enable_payloads.clone().unwrap_or_default().sketches);
    consumer.consume_env(config.env.clone());
    consumer.consume_forwarder_backoff_base(config.forwarder_backoff_base);
    consumer.consume_forwarder_backoff_factor(config.forwarder_backoff_factor);
    consumer.consume_forwarder_backoff_max(config.forwarder_backoff_max);
    consumer.consume_forwarder_connection_reset_interval(config.forwarder_connection_reset_interval);
    consumer.consume_forwarder_high_prio_buffer_size(config.forwarder_high_prio_buffer_size);
    consumer.consume_forwarder_http_protocol(config.forwarder_http_protocol.clone());
    consumer.consume_forwarder_max_concurrent_requests(config.forwarder_max_concurrent_requests);
    consumer.consume_forwarder_num_workers(config.forwarder_num_workers);
    consumer.consume_forwarder_outdated_file_in_days(config.forwarder_outdated_file_in_days);
    consumer.consume_forwarder_recovery_interval(config.forwarder_recovery_interval);
    consumer.consume_forwarder_recovery_reset(config.forwarder_recovery_reset);
    consumer.consume_forwarder_retry_queue_max_size(config.forwarder_retry_queue_max_size);
    consumer.consume_forwarder_retry_queue_payloads_max_size(config.forwarder_retry_queue_payloads_max_size);
    consumer.consume_forwarder_storage_max_disk_ratio(config.forwarder_storage_max_disk_ratio);
    consumer.consume_forwarder_storage_max_size_in_bytes(config.forwarder_storage_max_size_in_bytes);
    consumer.consume_forwarder_storage_path(config.forwarder_storage_path.clone());
    consumer.consume_forwarder_timeout(config.forwarder_timeout);
    consumer.consume_histogram_aggregates(config.histogram_aggregates.clone());
    consumer.consume_histogram_copy_to_distribution(config.histogram_copy_to_distribution);
    consumer.consume_histogram_copy_to_distribution_prefix(config.histogram_copy_to_distribution_prefix.clone());
    consumer.consume_log_format_rfc3339(config.log_format_rfc3339);
    consumer.consume_log_level(config.log_level.clone());
    consumer.consume_log_payloads(config.log_payloads);
    consumer.consume_metric_filterlist(config.metric_filterlist.clone());
    consumer.consume_metric_filterlist_match_prefix(config.metric_filterlist_match_prefix);
    consumer.consume_min_tls_version(config.min_tls_version.clone());
    consumer.consume_multi_region_failover_api_key(
        config.multi_region_failover.clone().unwrap_or_default().api_key.clone(),
    );
    consumer
        .consume_multi_region_failover_dd_url(config.multi_region_failover.clone().unwrap_or_default().dd_url.clone());
    consumer.consume_multi_region_failover_enabled(config.multi_region_failover.clone().unwrap_or_default().enabled);
    consumer.consume_multi_region_failover_failover_metrics(
        config
            .multi_region_failover
            .clone()
            .unwrap_or_default()
            .failover_metrics,
    );
    consumer.consume_multi_region_failover_metric_allowlist(
        config
            .multi_region_failover
            .clone()
            .unwrap_or_default()
            .metric_allowlist
            .clone(),
    );
    consumer.consume_multi_region_failover_site(config.multi_region_failover.clone().unwrap_or_default().site.clone());
    consumer.consume_no_proxy_nonexact_match(config.no_proxy_nonexact_match);
    consumer.consume_observability_pipelines_worker_metrics_enabled(
        config
            .observability_pipelines_worker
            .clone()
            .unwrap_or_default()
            .metrics
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_observability_pipelines_worker_metrics_url(
        config
            .observability_pipelines_worker
            .clone()
            .unwrap_or_default()
            .metrics
            .clone()
            .unwrap_or_default()
            .url
            .clone(),
    );
    consumer.consume_origin_detection_unified(config.origin_detection_unified);
    consumer.consume_otlp_config_logs_enabled(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .logs
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_otlp_config_metrics_enabled(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .metrics
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_otlp_config_receiver_protocols_grpc_endpoint(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .receiver
            .clone()
            .unwrap_or_default()
            .protocols
            .clone()
            .unwrap_or_default()
            .grpc
            .clone()
            .unwrap_or_default()
            .endpoint
            .clone(),
    );
    consumer.consume_otlp_config_receiver_protocols_grpc_max_recv_msg_size_mib(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .receiver
            .clone()
            .unwrap_or_default()
            .protocols
            .clone()
            .unwrap_or_default()
            .grpc
            .clone()
            .unwrap_or_default()
            .max_recv_msg_size_mib,
    );
    consumer.consume_otlp_config_receiver_protocols_grpc_transport(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .receiver
            .clone()
            .unwrap_or_default()
            .protocols
            .clone()
            .unwrap_or_default()
            .grpc
            .clone()
            .unwrap_or_default()
            .transport
            .clone(),
    );
    consumer.consume_otlp_config_receiver_protocols_http_endpoint(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .receiver
            .clone()
            .unwrap_or_default()
            .protocols
            .clone()
            .unwrap_or_default()
            .http
            .clone()
            .unwrap_or_default()
            .endpoint
            .clone(),
    );
    consumer.consume_otlp_config_traces_enabled(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .traces
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_otlp_config_traces_internal_port(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .traces
            .clone()
            .unwrap_or_default()
            .internal_port,
    );
    consumer.consume_otlp_config_traces_probabilistic_sampler_sampling_percentage(
        config
            .otlp_config
            .clone()
            .unwrap_or_default()
            .traces
            .clone()
            .unwrap_or_default()
            .probabilistic_sampler
            .clone()
            .unwrap_or_default()
            .sampling_percentage,
    );
    consumer.consume_provider_kind(config.provider_kind.clone());
    consumer.consume_proxy_http(config.proxy.clone().unwrap_or_default().http.clone());
    consumer.consume_proxy_https(config.proxy.clone().unwrap_or_default().https.clone());
    consumer.consume_proxy_no_proxy(config.proxy.clone().unwrap_or_default().no_proxy.clone());
    consumer.consume_serializer_compressor_kind(config.serializer_compressor_kind.clone());
    consumer.consume_serializer_max_payload_size(config.serializer_max_payload_size);
    consumer.consume_serializer_max_series_payload_size(config.serializer_max_series_payload_size);
    consumer.consume_serializer_max_series_points_per_payload(config.serializer_max_series_points_per_payload);
    consumer.consume_serializer_max_series_uncompressed_payload_size(
        config.serializer_max_series_uncompressed_payload_size,
    );
    consumer.consume_serializer_max_uncompressed_payload_size(config.serializer_max_uncompressed_payload_size);
    consumer.consume_serializer_zstd_compressor_level(config.serializer_zstd_compressor_level);
    consumer.consume_site(config.site.clone());
    consumer.consume_skip_ssl_validation(config.skip_ssl_validation);
    consumer.consume_statsd_forward_host(config.statsd_forward_host.clone());
    consumer.consume_statsd_forward_port(config.statsd_forward_port);
    consumer.consume_statsd_metric_blocklist(config.statsd_metric_blocklist.clone());
    consumer.consume_statsd_metric_blocklist_match_prefix(config.statsd_metric_blocklist_match_prefix);
    consumer.consume_statsd_metric_namespace(config.statsd_metric_namespace.clone());
    consumer.consume_statsd_metric_namespace_blacklist(config.statsd_metric_namespace_blacklist.clone());
    consumer.consume_syslog_rfc(config.syslog_rfc);
    consumer.consume_syslog_uri(config.syslog_uri.clone());
    consumer.consume_use_proxy_for_cloud_metadata(config.use_proxy_for_cloud_metadata);
    consumer.consume_use_v2_api_series(config.use_v2_api.clone().unwrap_or_default().series);
    consumer.consume_vector_metrics_enabled(
        config
            .vector
            .clone()
            .unwrap_or_default()
            .metrics
            .clone()
            .unwrap_or_default()
            .enabled,
    );
    consumer.consume_vector_metrics_url(
        config
            .vector
            .clone()
            .unwrap_or_default()
            .metrics
            .clone()
            .unwrap_or_default()
            .url
            .clone(),
    );
    consumer.consume_vsock_addr(config.vsock_addr.clone());
}
