[package]
name = "datadog-agent-remote-config"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
datadog-agent-commons = { workspace = true }
saluki-core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_variant = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }

[build-dependencies]

[lints]
workspace = true
