// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::*;


static FLUSH_TIMEOUT_SECS_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "flush_timeout_secs",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

static SERIALIZER_MAX_METRICS_PER_PAYLOAD_SCHEMA: SchemaEntry = SchemaEntry {
    schema: Schema::Saluki,
    yaml_path: "serializer_max_metrics_per_payload",
    env_vars: &[],
    value_type: ValueType::Integer,
    default: None,
};

crate::declare_annotations! {
    /// `env`-Agent environment name
    ENV = SalukiAnnotation {
        schema: &super::schema::ENV,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_APM_STATS_ENCODER_CONFIGURATION, structs::DATADOG_TRACE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Traces]),
    };
    /// `log_payloads`-Debug-log decoded payload contents before encoding
    LOG_PAYLOADS = SalukiAnnotation {
        schema: &super::schema::LOG_PAYLOADS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_EVENTS_CONFIGURATION, structs::DATADOG_METRICS_CONFIGURATION, structs::DATADOG_SERVICE_CHECKS_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD, Pipeline::Traces]),
    };
    /// `serializer_compressor_kind`-Payload compression algorithm
    SERIALIZER_COMPRESSOR_KIND = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_COMPRESSOR_KIND,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_EVENTS_CONFIGURATION, structs::DATADOG_LOGS_CONFIGURATION, structs::DATADOG_METRICS_CONFIGURATION, structs::DATADOG_SERVICE_CHECKS_CONFIGURATION, structs::DATADOG_TRACE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `serializer_max_payload_size`-Max compressed payload size (generic)
    SERIALIZER_MAX_PAYLOAD_SIZE = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_MAX_PAYLOAD_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_EVENTS_CONFIGURATION, structs::DATADOG_METRICS_CONFIGURATION, structs::DATADOG_SERVICE_CHECKS_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_max_series_payload_size`-Max compressed V2 series payload size
    SERIALIZER_MAX_SERIES_PAYLOAD_SIZE = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_MAX_SERIES_PAYLOAD_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_max_series_points_per_payload`-Max data points per series payload
    SERIALIZER_MAX_SERIES_POINTS_PER_PAYLOAD = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_MAX_SERIES_POINTS_PER_PAYLOAD,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_max_series_uncompressed_payload_size`-Max uncompressed V2 series payload size
    SERIALIZER_MAX_SERIES_UNCOMPRESSED_PAYLOAD_SIZE = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_MAX_SERIES_UNCOMPRESSED_PAYLOAD_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_max_uncompressed_payload_size`-Max uncompressed payload size (generic)
    SERIALIZER_MAX_UNCOMPRESSED_PAYLOAD_SIZE = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_MAX_UNCOMPRESSED_PAYLOAD_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_EVENTS_CONFIGURATION, structs::DATADOG_METRICS_CONFIGURATION, structs::DATADOG_SERVICE_CHECKS_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `serializer_zstd_compressor_level`-Zstd compression level
    SERIALIZER_ZSTD_COMPRESSOR_LEVEL = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_ZSTD_COMPRESSOR_LEVEL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_EVENTS_CONFIGURATION, structs::DATADOG_LOGS_CONFIGURATION, structs::DATADOG_METRICS_CONFIGURATION, structs::DATADOG_SERVICE_CHECKS_CONFIGURATION, structs::DATADOG_TRACE_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `use_v2_api.series`-Send series via V2 protobuf endpoint
    USE_V2_API_SERIES = SalukiAnnotation {
        schema: &super::schema::USE_V2_API_SERIES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
    /// `flush_timeout_secs`
    FLUSH_TIMEOUT_SECS = SalukiAnnotation {
        schema: &FLUSH_TIMEOUT_SECS_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_APM_STATS_ENCODER_CONFIGURATION, structs::DATADOG_METRICS_CONFIGURATION, structs::DATADOG_TRACE_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::Traces, Pipeline::DogStatsD]),
    };
    /// `serializer_max_metrics_per_payload`
    SERIALIZER_MAX_METRICS_PER_PAYLOAD = SalukiAnnotation {
        schema: &SERIALIZER_MAX_METRICS_PER_PAYLOAD_SCHEMA,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::DATADOG_METRICS_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::Checks, Pipeline::DogStatsD]),
    };
}
