// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::*;


crate::declare_annotations! {
    /// `additional_endpoints`-Dual-ship to extra endpoints
    ADDITIONAL_ENDPOINTS = SalukiAnnotation {
        schema: &super::schema::ADDITIONAL_ENDPOINTS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: Some("{\"smoke-host-1.example.com\": [\"smoke-api-key\"]}"),
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `allow_arbitrary_tags`-Relax backend tag validation via HTTP header
    ALLOW_ARBITRARY_TAGS = SalukiAnnotation {
        schema: &super::schema::ALLOW_ARBITRARY_TAGS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_ALLOW_ARBITRARY_TAGS"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `api_key`-API key for endpoint auth
    API_KEY = SalukiAnnotation {
        schema: &super::schema::API_KEY,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `dd_url`-Override intake endpoint URL
    DD_URL = SalukiAnnotation {
        schema: &super::schema::DD_URL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_backoff_base`-Retry backoff base (secs)
    FORWARDER_BACKOFF_BASE = SalukiAnnotation {
        schema: &super::schema::FORWARDER_BACKOFF_BASE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_backoff_factor`-Retry backoff jitter factor
    FORWARDER_BACKOFF_FACTOR = SalukiAnnotation {
        schema: &super::schema::FORWARDER_BACKOFF_FACTOR,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_backoff_max`-Retry backoff ceiling (secs)
    FORWARDER_BACKOFF_MAX = SalukiAnnotation {
        schema: &super::schema::FORWARDER_BACKOFF_MAX,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_connection_reset_interval`-HTTP conn reset interval (secs)
    FORWARDER_CONNECTION_RESET_INTERVAL = SalukiAnnotation {
        schema: &super::schema::FORWARDER_CONNECTION_RESET_INTERVAL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_high_prio_buffer_size`-High-priority request queue size
    FORWARDER_HIGH_PRIO_BUFFER_SIZE = SalukiAnnotation {
        schema: &super::schema::FORWARDER_HIGH_PRIO_BUFFER_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_http_protocol`-HTTP version selection (auto/http1/http2)
    FORWARDER_HTTP_PROTOCOL = SalukiAnnotation {
        schema: &super::schema::FORWARDER_HTTP_PROTOCOL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_num_workers`-Concurrent forwarder workers
    FORWARDER_NUM_WORKERS = SalukiAnnotation {
        schema: &super::schema::FORWARDER_NUM_WORKERS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_outdated_file_in_days`-Days before retry files are deleted
    FORWARDER_OUTDATED_FILE_IN_DAYS = SalukiAnnotation {
        schema: &super::schema::FORWARDER_OUTDATED_FILE_IN_DAYS,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_recovery_interval`-Backoff recovery decrease factor
    FORWARDER_RECOVERY_INTERVAL = SalukiAnnotation {
        schema: &super::schema::FORWARDER_RECOVERY_INTERVAL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_recovery_reset`-Reset errors on success
    FORWARDER_RECOVERY_RESET = SalukiAnnotation {
        schema: &super::schema::FORWARDER_RECOVERY_RESET,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_retry_queue_max_size`-Retry queue max size (depr.)
    FORWARDER_RETRY_QUEUE_MAX_SIZE = SalukiAnnotation {
        schema: &super::schema::FORWARDER_RETRY_QUEUE_MAX_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_retry_queue_payloads_max_size`-Retry queue max size (bytes)
    FORWARDER_RETRY_QUEUE_PAYLOADS_MAX_SIZE = SalukiAnnotation {
        schema: &super::schema::FORWARDER_RETRY_QUEUE_PAYLOADS_MAX_SIZE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_storage_max_disk_ratio`-Max disk usage ratio for retry
    FORWARDER_STORAGE_MAX_DISK_RATIO = SalukiAnnotation {
        schema: &super::schema::FORWARDER_STORAGE_MAX_DISK_RATIO,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_storage_max_size_in_bytes`-Max on-disk retry storage size
    FORWARDER_STORAGE_MAX_SIZE_IN_BYTES = SalukiAnnotation {
        schema: &super::schema::FORWARDER_STORAGE_MAX_SIZE_IN_BYTES,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_storage_path`-On-disk retry storage directory
    FORWARDER_STORAGE_PATH = SalukiAnnotation {
        schema: &super::schema::FORWARDER_STORAGE_PATH,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_timeout`-Forwarder HTTP request timeout
    FORWARDER_TIMEOUT = SalukiAnnotation {
        schema: &super::schema::FORWARDER_TIMEOUT,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: Some(ValueType::Integer),
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `min_tls_version`-Minimum TLS version for HTTPS connections
    MIN_TLS_VERSION = SalukiAnnotation {
        schema: &super::schema::MIN_TLS_VERSION,
        support_level: SupportLevel::Partial,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_MIN_TLS_VERSION"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `observability_pipelines_worker.metrics.enabled`-Route metrics to OPW instance
    OBSERVABILITY_PIPELINES_WORKER_METRICS_ENABLED = SalukiAnnotation {
        schema: &super::schema::OBSERVABILITY_PIPELINES_WORKER_METRICS_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_ENABLED"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `observability_pipelines_worker.metrics.url`-OPW metrics intake URL
    OBSERVABILITY_PIPELINES_WORKER_METRICS_URL = SalukiAnnotation {
        schema: &super::schema::OBSERVABILITY_PIPELINES_WORKER_METRICS_URL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_URL"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `site`-Datadog site domain
    SITE = SalukiAnnotation {
        schema: &super::schema::SITE,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `skip_ssl_validation`-Skip TLS cert validation
    SKIP_SSL_VALIDATION = SalukiAnnotation {
        schema: &super::schema::SKIP_SSL_VALIDATION,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_SKIP_SSL_VALIDATION"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `vector.metrics.enabled`-Route metrics to OPW (legacy alias)
    VECTOR_METRICS_ENABLED = SalukiAnnotation {
        schema: &super::schema::VECTOR_METRICS_ENABLED,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_VECTOR_METRICS_ENABLED"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `vector.metrics.url`-OPW metrics intake URL (legacy alias)
    VECTOR_METRICS_URL = SalukiAnnotation {
        schema: &super::schema::VECTOR_METRICS_URL,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: Some(&["DD_VECTOR_METRICS_URL"]),
        used_by: &[structs::FORWARDER_CONFIGURATION],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
