// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::*;


crate::declare_annotations! {
    /// `cmd_port`-Datadog Agent IPC/CMD API port
    CMD_PORT = SalukiAnnotation {
        schema: &super::schema::CMD_PORT,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::REMOTE_AGENT_CLIENT_CONFIGURATION],
        value_type_override: None,
        test_json: Some("5101"),
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `log_format_rfc3339`-Use RFC 3339 timestamps in log output
    LOG_FORMAT_RFC3339 = SalukiAnnotation {
        schema: &super::schema::LOG_FORMAT_RFC3339,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `syslog_rfc`-Use RFC-style syslog header
    SYSLOG_RFC = SalukiAnnotation {
        schema: &super::schema::SYSLOG_RFC,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `syslog_uri`-Syslog destination URI
    SYSLOG_URI = SalukiAnnotation {
        schema: &super::schema::SYSLOG_URI,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::GET_TYPED],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `vsock_addr`-vsock address for Agent IPC endpoint
    VSOCK_ADDR = SalukiAnnotation {
        schema: &super::schema::VSOCK_ADDR,
        support_level: SupportLevel::Full,
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[structs::REMOTE_AGENT_CLIENT_CONFIGURATION],
        value_type_override: None,
        test_json: Some("\"host\""),
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
