// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT

use crate::config_registry::{Pipeline, PipelineAffinity, SalukiAnnotation, Schema, SchemaEntry, Severity, SupportLevel, ValueType, structs};

#[allow(dead_code)]
mod schema;

mod aggregate;
mod containerd;
mod dogstatsd;
mod dogstatsd_mapper;
mod dogstatsd_prefix_filter;
mod encoders;
mod forwarder;
mod get_typed;
mod mrf;
mod otlp;
mod proxy;
mod tag_filterlist;
mod trace_obfuscation;

pub(super) mod unsupported;

use std::sync::LazyLock;

pub static SUPPORTED_ANNOTATIONS: LazyLock<Vec<&'static SalukiAnnotation>> = LazyLock::new(|| {
    let mut v: Vec<&'static SalukiAnnotation> = Vec::new();
    v.extend_from_slice(aggregate::ALL);
    v.extend_from_slice(containerd::ALL);
    v.extend_from_slice(dogstatsd::ALL);
    v.extend_from_slice(dogstatsd_mapper::ALL);
    v.extend_from_slice(dogstatsd_prefix_filter::ALL);
    v.extend_from_slice(encoders::ALL);
    v.extend_from_slice(forwarder::ALL);
    v.extend_from_slice(get_typed::ALL);
    v.extend_from_slice(mrf::ALL);
    v.extend_from_slice(otlp::ALL);
    v.extend_from_slice(proxy::ALL);
    v.extend_from_slice(tag_filterlist::ALL);
    v.extend_from_slice(trace_obfuscation::ALL);
    v
});

pub static UNSUPPORTED_ANNOTATIONS: LazyLock<Vec<&'static SalukiAnnotation>> = LazyLock::new(|| {
    let mut v: Vec<&'static SalukiAnnotation> = Vec::new();
    v.extend_from_slice(unsupported::ALL);
    v
});

pub static ALL_ANNOTATIONS: LazyLock<Vec<&'static SalukiAnnotation>> = LazyLock::new(|| {
    let mut v = SUPPORTED_ANNOTATIONS.clone();
    v.extend_from_slice(&UNSUPPORTED_ANNOTATIONS);
    v
});
