// @generated by build.rs from schema_overlay.yaml — DO NOT EDIT
#[allow(unused_imports)]
use super::*;

crate::declare_annotations! {
    /// `aggregator_buffer_size`-Channel buffer depth for aggregator queues
    AGGREGATOR_BUFFER_SIZE = SalukiAnnotation {
        schema: &super::schema::AGGREGATOR_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `aggregator_flush_metrics_and_serialize_in_parallel_buffer_size`-Parallel flush: series/sketch buffer size
    AGGREGATOR_FLUSH_METRICS_AND_SERIALIZE_IN_PARALLEL_BUFFER_SIZE = SalukiAnnotation {
        schema: &super::schema::AGGREGATOR_FLUSH_METRICS_AND_SERIALIZE_IN_PARALLEL_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `aggregator_flush_metrics_and_serialize_in_parallel_chan_size`-Parallel flush: channel size
    AGGREGATOR_FLUSH_METRICS_AND_SERIALIZE_IN_PARALLEL_CHAN_SIZE = SalukiAnnotation {
        schema: &super::schema::AGGREGATOR_FLUSH_METRICS_AND_SERIALIZE_IN_PARALLEL_CHAN_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `aggregator_stop_timeout`-Timeout (s) for aggregator flush on stop
    AGGREGATOR_STOP_TIMEOUT = SalukiAnnotation {
        schema: &super::schema::AGGREGATOR_STOP_TIMEOUT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `aggregator_use_tags_store`-Enable shared tag deduplication store
    AGGREGATOR_USE_TAGS_STORE = SalukiAnnotation {
        schema: &super::schema::AGGREGATOR_USE_TAGS_STORE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_disable_verbose_logs`-Suppress noisy parse error logs
    DOGSTATSD_DISABLE_VERBOSE_LOGS = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_DISABLE_VERBOSE_LOGS,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_experimental_http.enabled`-Enable experimental HTTP/H2C DSD listener
    DOGSTATSD_EXPERIMENTAL_HTTP_ENABLED = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_EXPERIMENTAL_HTTP_ENABLED,
        support_level: SupportLevel::Incompatible(Severity::High),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_experimental_http.listen_address`-Bind address for experimental HTTP DSD listener
    DOGSTATSD_EXPERIMENTAL_HTTP_LISTEN_ADDRESS = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_EXPERIMENTAL_HTTP_LISTEN_ADDRESS,
        support_level: SupportLevel::Incompatible(Severity::High),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_pipe_name`-Windows named pipe path
    DOGSTATSD_PIPE_NAME = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_PIPE_NAME,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_stats_buffer`-Internal stats buffer size
    DOGSTATSD_STATS_BUFFER = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_STATS_BUFFER,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `dogstatsd_windows_pipe_security_descriptor`-Windows named pipe ACL descriptor
    DOGSTATSD_WINDOWS_PIPE_SECURITY_DESCRIPTOR = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_WINDOWS_PIPE_SECURITY_DESCRIPTOR,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD]),
    };
    /// `enable_json_stream_shared_compressor_buffers`-Pre-allocate shared compressor buffers
    ENABLE_JSON_STREAM_SHARED_COMPRESSOR_BUFFERS = SalukiAnnotation {
        schema: &super::schema::ENABLE_JSON_STREAM_SHARED_COMPRESSOR_BUFFERS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `forwarder_apikey_validation_interval`-API key check interval (minutes)
    FORWARDER_APIKEY_VALIDATION_INTERVAL = SalukiAnnotation {
        schema: &super::schema::FORWARDER_APIKEY_VALIDATION_INTERVAL,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `serializer_experimental_use_v3_api.compression_level`-V3 API zstd compression level
    SERIALIZER_EXPERIMENTAL_USE_V3_API_COMPRESSION_LEVEL = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_COMPRESSION_LEVEL,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.series.endpoints`-Endpoints enabled for V3 series API
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_ENDPOINTS = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_ENDPOINTS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.series.validate`-Dual-send v2+v3 series for validation
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_VALIDATE = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SERIES_VALIDATE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.sketches.endpoints`-Endpoints enabling v3 sketches API
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_ENDPOINTS = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_ENDPOINTS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `serializer_experimental_use_v3_api.sketches.validate`-Dual-send v2+v3 sketches for validation
    SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_VALIDATE = SalukiAnnotation {
        schema: &super::schema::SERIALIZER_EXPERIMENTAL_USE_V3_API_SKETCHES_VALIDATE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::Pipelines(&[Pipeline::DogStatsD, Pipeline::Checks, Pipeline::Traces]),
    };
    /// `sslkeylogfile`-TLS key log file path
    SSLKEYLOGFILE = SalukiAnnotation {
        schema: &super::schema::SSLKEYLOGFILE,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `tls_handshake_timeout`-HTTP TLS handshake timeout
    TLS_HANDSHAKE_TIMEOUT = SalukiAnnotation {
        schema: &super::schema::TLS_HANDSHAKE_TIMEOUT,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `autoscaling.failover.enabled`-Enable autoscaling failover metric routing
    AUTOSCALING_FAILOVER_ENABLED = SalukiAnnotation {
        schema: &super::schema::AUTOSCALING_FAILOVER_ENABLED,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `autoscaling.failover.metrics`-Metric names forwarded to DCA for failover
    AUTOSCALING_FAILOVER_METRICS = SalukiAnnotation {
        schema: &super::schema::AUTOSCALING_FAILOVER_METRICS,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `dogstatsd_stats_enable`-Enable internal stats endpoint
    DOGSTATSD_STATS_ENABLE = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_STATS_ENABLE,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `dogstatsd_stats_port`-Internal stats endpoint port
    DOGSTATSD_STATS_PORT = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_STATS_PORT,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `dogstatsd_telemetry_enabled_listener_id`-Per-listener telemetry tagging
    DOGSTATSD_TELEMETRY_ENABLED_LISTENER_ID = SalukiAnnotation {
        schema: &super::schema::DOGSTATSD_TELEMETRY_ENABLED_LISTENER_ID,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_flush_to_disk_mem_ratio`-Mem-to-disk flush threshold
    FORWARDER_FLUSH_TO_DISK_MEM_RATIO = SalukiAnnotation {
        schema: &super::schema::FORWARDER_FLUSH_TO_DISK_MEM_RATIO,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_low_prio_buffer_size`-Low-priority request queue size
    FORWARDER_LOW_PRIO_BUFFER_SIZE = SalukiAnnotation {
        schema: &super::schema::FORWARDER_LOW_PRIO_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_max_concurrent_requests`-Max concurrent HTTP requests
    FORWARDER_MAX_CONCURRENT_REQUESTS = SalukiAnnotation {
        schema: &super::schema::FORWARDER_MAX_CONCURRENT_REQUESTS,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_requeue_buffer_size`-In-memory re-queue buffer size
    FORWARDER_REQUEUE_BUFFER_SIZE = SalukiAnnotation {
        schema: &super::schema::FORWARDER_REQUEUE_BUFFER_SIZE,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_retry_queue_capacity_time_interval_sec`-Retry queue time-based capacity
    FORWARDER_RETRY_QUEUE_CAPACITY_TIME_INTERVAL_SEC = SalukiAnnotation {
        schema: &super::schema::FORWARDER_RETRY_QUEUE_CAPACITY_TIME_INTERVAL_SEC,
        support_level: SupportLevel::Incompatible(Severity::Medium),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `forwarder_stop_timeout`-Timeout (s) for forwarder graceful stop
    FORWARDER_STOP_TIMEOUT = SalukiAnnotation {
        schema: &super::schema::FORWARDER_STOP_TIMEOUT,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `heroku_dyno`-Heroku dyno telemetry mode
    HEROKU_DYNO = SalukiAnnotation {
        schema: &super::schema::HEROKU_DYNO,
        support_level: SupportLevel::Incompatible(Severity::High),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `telemetry.dogstatsd.aggregator_channel_latency_buckets`-Histogram buckets: DSD aggregator channel lag
    TELEMETRY_DOGSTATSD_AGGREGATOR_CHANNEL_LATENCY_BUCKETS = SalukiAnnotation {
        schema: &super::schema::TELEMETRY_DOGSTATSD_AGGREGATOR_CHANNEL_LATENCY_BUCKETS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `telemetry.dogstatsd.listeners_channel_latency_buckets`-Histogram buckets: listener channel latency
    TELEMETRY_DOGSTATSD_LISTENERS_CHANNEL_LATENCY_BUCKETS = SalukiAnnotation {
        schema: &super::schema::TELEMETRY_DOGSTATSD_LISTENERS_CHANNEL_LATENCY_BUCKETS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `telemetry.dogstatsd.listeners_latency_buckets`-Histogram buckets: listener processing
    TELEMETRY_DOGSTATSD_LISTENERS_LATENCY_BUCKETS = SalukiAnnotation {
        schema: &super::schema::TELEMETRY_DOGSTATSD_LISTENERS_LATENCY_BUCKETS,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
    /// `telemetry.dogstatsd_origin`-Per-origin processed-metrics telemetry
    TELEMETRY_DOGSTATSD_ORIGIN = SalukiAnnotation {
        schema: &super::schema::TELEMETRY_DOGSTATSD_ORIGIN,
        support_level: SupportLevel::Incompatible(Severity::Low),
        additional_yaml_paths: &[],
        env_var_override: None,
        used_by: &[],
        value_type_override: None,
        test_json: None,
        pipeline_affinity: PipelineAffinity::CrossCutting,
    };
}
